#!/bin/bash
set -eou pipefail

parent_dir="$(pwd)"

function back_to_parent {
    cd "${parent_dir}"
}
trap back_to_parent EXIT

for subdir in ./*/; do
    cd "${subdir}"
    "${@}"
    back_to_parent
done
