#+TITLE: Config

* Overview
My attempt at making a literate ~config.el~.

* Personal Info
This is used by GPG and many other things.
#+BEGIN_SRC emacs-lisp
(setq user-full-name "Caleb McCombs"
      user-mail-address "<replace me locally (comp-setup/emacs-doom/config.org)>")
#+END_SRC

* Projectile
Projects! Yay!
** Project Directories
Where to scan for Project directories.
#+BEGIN_SRC emacs-lisp
(setq projectile-project-search-path '("~/Projects" "~/Workspaces"))
#+END_SRC

* Global Settings
** Subword Mode
Allow moving by word (~A-f~, ~A-b~) within large identifiers. Generally allows movement through CamelCase words.
#+BEGIN_SRC emacs-lisp
(global-subword-mode 1)
#+END_SRC
** Global Line Number Mode
Always show line numbers, every buffer. Straight from [[https://www.emacswiki.org/emacs/LineNumbers][here]].
#+BEGIN_SRC emacs-lisp
(when (version<= "26.0.50" emacs-version )
  (global-display-line-numbers-mode))
#+END_SRC

* CA Configuration
DOOM Emacs may provide a ca-bundle. Point GnuTLS at that rather than the system provided one.

#+BEGIN_SRC emacs-lisp
(let ((local-cert-bundle-path "~/.config/doom/ca-bundle.crt"))
  (when (file-exists-p local-cert-bundle-path)
    ;;; Code:
    (setq gnutls-trustfiles local-cert-bundle-path)))
#+END_SRC
** TODO Consider the ramifications of this in the face of internal CAs.

* Org Mode Customizations
** Closing TODO Behavior
When I mark a TODO item as DONE, I would like a record of when that happens.
Could also be set to `note` instead of `time` if I want to record a closing note in addition to a timestamp.
#+BEGIN_SRC emacs-lisp
(setq org-log-done 'time)
#+END_SRC

** DEPRECATED: Org Reveal Mode
Enable it and set the location of reveal.js
#+BEGIN_SRC emacs-lisp
(require 'ox-reveal)
; If you install reveal-md on Arch, the module is here.
(setq org-reveal-root "file:///usr/lib/reveal-md/node_modules/reveal.js")
#+END_SRC

* Custom Key Bindings
#+BEGIN_SRC emacs-lisp
;; Enable the Treemacs toggle.
(map! "<f9>" #'treemacs)
#+END_SRC
