#+TITLE: Config

* Overview
My attempt at making a literate ~config.el~.

* Projectile
Projects! Yay!
** Brazil Support
This is about as basic a support for Brazil as I could possibly do... Bases the detection of a Projectile project on the existence of a ~packageInfo~ file.
#+BEGIN_SRC emacs-lisp
(projectile-register-project-type 'Brazil-Workspace '("packageInfo"))
#+END_SRC

Determine a project type of brazil package based on the existence of the ~Config~ file. This doesn't pan out that well though because Projectile doesn't like projects in other projects.
#+BEGIN_SRC emacs-lisp
;(projectile-register-project-type 'Brazil-Package '("Config")
;                                  :compile "brazil-build")
#+END_SRC

** Project Directories
Where to scan for Project directories.
#+BEGIN_SRC emacs-lisp
(setq projectile-project-search-path '("~/Projects" "~/Workspaces"))
#+END_SRC

* Subword Mode
Allow moving by word (~A-f~, ~A-b~) within large identifiers.
#+BEGIN_SRC emacs-lisp
(global-subword-mode 1)
#+END_SRC

* CA Configuration
DOOM Emacs may provide a ca-bundle. Point GnuTLS at that rather than the system provided one.

#+BEGIN_SRC emacs-lisp
(let ((local-cert-bundle-path "~/.config/doom/ca-bundle.crt"))
  (when (file-exists-p local-cert-bundle-path)
    ;;; Code:
    (setq gnutls-trustfiles local-cert-bundle-path)))
#+END_SRC
** TODO Consider the ramifications of this in light of Amazon's internal CAs.

* Custom Key Bindings
#+BEGIN_SRC emacs-lisp
;; Enable the Treemacs toggle.
(map! "<f9>" #'treemacs)
#+END_SRC
